// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbk-RN9Hds_IQVCYO38vLa6D7ot4PHTs',
    appId: '1:661621922390:web:fe8cf61c445afb58f1f9f7',
    messagingSenderId: '661621922390',
    projectId: 'stimutech-wind-turbine-540a2',
    authDomain: 'stimutech-wind-turbine-540a2.firebaseapp.com',
    storageBucket: 'stimutech-wind-turbine-540a2.appspot.com',
    measurementId: 'G-NGE436KW47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1eZQONiR6zZqe2qEYHw0Ms0p5LDnkUk',
    appId: '1:661621922390:android:8227c049be33ec3ef1f9f7',
    messagingSenderId: '661621922390',
    projectId: 'stimutech-wind-turbine-540a2',
    storageBucket: 'stimutech-wind-turbine-540a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp3yjd3RijFDFQ5T0DhyX6vCo9qS3Dhxw',
    appId: '1:661621922390:ios:ea3d045c15cd9732f1f9f7',
    messagingSenderId: '661621922390',
    projectId: 'stimutech-wind-turbine-540a2',
    storageBucket: 'stimutech-wind-turbine-540a2.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp3yjd3RijFDFQ5T0DhyX6vCo9qS3Dhxw',
    appId: '1:661621922390:ios:33d3a671044f7a90f1f9f7',
    messagingSenderId: '661621922390',
    projectId: 'stimutech-wind-turbine-540a2',
    storageBucket: 'stimutech-wind-turbine-540a2.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
